# Generated by Django 5.0.6 on 2024-05-14 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bebida', models.CharField(max_length=72, null=True)),
                ('Acompanhamento', models.CharField(max_length=72)),
                ('StatusPedido', models.CharField(choices=[('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado'), ('PAGAMENTO', 'Aguardando pagamento')], max_length=72, null=True)),
                ('DataPed', models.DateField(auto_now_add=True, null=True)),
                ('NomeCli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
