# Generated by Django 5.0.6 on 2024-05-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeCli', models.CharField(max_length=72, null=True)),
                ('Bebida', models.CharField(max_length=72, null=True)),
                ('Acompanhamento', models.CharField(max_length=72)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StatusPedido', models.CharField(choices=[('Aprovado', 'APROVADO'), ('Cancelado', 'CANCELADO'), ('Aguardando pagamento', 'PAGAMENTO')], max_length=72, null=True)),
                ('DataPed', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
