# Generated by Django 4.2.7 on 2024-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ObsPed',
            field=models.CharField(max_length=72, null=True),
        ),
    ]
