# Generated by Django 4.2.7 on 2024-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_obsped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='StatusPedido',
            field=models.CharField(choices=[('Aprovado', 'APROVADO'), ('Cancelado', 'CANCELADO'), ('Aguardando', 'PAGAMENTO')], max_length=72, null=True),
        ),
    ]
