# Generated by Django 5.0.6 on 2024-05-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pedido_statuspedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='StatusPedido',
            field=models.CharField(choices=[('Aprovado', 'APROVADO'), ('Cancelado', 'CANCELADO'), ('Aguardando pagamento', 'PAGAMENTO'), ('Aprovado', 'APROVADO')], max_length=72, null=True),
        ),
    ]
